# Generated by Django 2.2 on 2020-10-06 11:42

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201003_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(max_length=500, upload_to=blog.models.upload_location),
        ),
    ]
