# Generated by Django 2.2 on 2020-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
